### ISSUE TITLE
RNS3.put is not a function

### ISSUE THREAD

**Issue by shaikhussian** [benjreinhart/react-native-aws3#1]
hai , i am happy when i saw this module, when i follow there procedure as you mentioned in repo, i am getting an error like RNS3.put is not a function, RNS3.put is undefined 
![simulator screen shot 25-mar-2016 4 33 54 pm](https://cloud.githubusercontent.com/assets/11956308/14043188/74606bde-f2a7-11e5-91bc-359d87c6ad45.png)

**Comment by benjreinhart** [comment]
Hey there, thanks for trying it out. Sorry you're having issues.

Have you made sure that when you installed you killed the packager and restarted the app? Might also try clearing packager cache, running `watchman watch-del-all`, and/or clearing node modules, clearing npm cache and re-installing. I've pulled this into two existing RN projects and it has worked fine for me. 

Also, you're importing it correctly, right? Either:

```javascript
import { RNS3 } from 'react-native-aws3';
```

Or 

```javascript
const RNS3 = require('react-native-aws3').RNS3
```

**Comment by shaikhussian** [comment]
@benjreinhart thanks for your response now it was working for me
