### ISSUE TITLE
Use different endpoints

### ISSUE THREAD

**Issue by devhyunjae** [benjreinhart/react-native-aws3#13]
Checked that this libs s3 endpoint is

`s3.amazonaws.com`

Following this document,

http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

needs to be set differently depending on the region.

**Comment by benjreinhart** [comment]
Interesting, will take a look. Thanks

**Comment by voidale** [comment]
+1

**Comment by voidale** [comment]
this can now be closed https://github.com/benjreinhart/react-native-aws3/pull/20

**Comment by benjreinhart** [comment]
Yep, I'll close it when the next version is released, which should be in a bit
