### ISSUE TITLE
No suitable way to upload multiple images

### ISSUE THREAD

**Issue by alaingoldman** [benjreinhart/react-native-aws3#23]
Hey benjreinhart,
I was wondering if there is any way you could possible upload multiple photos at once.

**Comment by benjreinhart** [comment]
Agreed that it could be nice to provide an API that handles multiple uploads with a callback when all have finished, but until then, is there a reason why just calling `RNS3.put` multiple times won't work?

**Comment by alaingoldman** [comment]
No you're right multiple RNS3.put works totally fine. I was just wondering.  Thanks for the feedback.

**Comment by benjreinhart** [comment]
No problem
