### ISSUE TITLE
Policy expired error

### ISSUE THREAD

**Issue by agrass** [benjreinhart/react-native-aws3#28]
Hi!

I'm getting this error:

```
<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>AccessDenied</Code>
<Message>Invalid according to Policy: Policy expired.</Message>
<RequestId></RequestId>
<HostId>w//</HostId></Error><?xml version="1.0" encoding="UTF-8"?>\n
<Error><Code>AccessDenied</Code>
<Message>Invalid according to Policy: Policy expired.</Message>
<RequestId></RequestId>
<HostId>
</HostId></Error>

```
I tried to add more timeDelta, but I can't fix this issue. Anyone with same problem??

Thanks

**Comment by benjreinhart** [comment]
Did you try this without the timedelta?

**Comment by agrass** [comment]
Thanks for the response. I already fixed it updating to last version (0.0.4) and added 24 hours for timedelta.

**Comment by sibelius** [comment]
@agrass could you share your solution?

I think this is related https://github.com/benjreinhart/react-native-aws3/issues/58

**Comment by agrass** [comment]
I just added some timeDelta, to prevent this when the time in the phone is wrong

**Comment by sibelius** [comment]
`timeDelta: -24*60*60*1000` works great

tks
