### ISSUE TITLE
Possible Unhandled Promise Rejection

### ISSUE THREAD

**Issue by emilhm** [benjreinhart/react-native-aws3#29]
Hi, I'm getting the following error when trying to upload an image:

![captura de pantalla 2017-02-20 a las 4 21 45 p m](https://cloud.githubusercontent.com/assets/6857933/23140587/d96970b6-f788-11e6-9d7e-7bd2519cacf4.png)

and this is my code: 

![captura de pantalla 2017-02-20 a las 4 34 01 p m](https://cloud.githubusercontent.com/assets/6857933/23140924/8d3aae06-f78a-11e6-904c-a15da9ac58e5.png)

**Comment by emilhm** [comment]
i fixed this error adding the catch statement

![captura de pantalla 2017-02-21 a las 10 06 29 a m](https://cloud.githubusercontent.com/assets/6857933/23168291/16c60a1a-f81e-11e6-8518-f300e2a76386.png)

**Comment by saikiranoptisol** [comment]
@emilhm how didi you fix this issue. For me its happening the same

**Comment by emilhm** [comment]
I just added a catch statement to the promise. Can you put a screenshot of your code? @saikiranoptisol

**Comment by saikiranoptisol** [comment]
@emilhm  thank you its working after keeping catch
