### ISSUE TITLE
Feature Request- Please make AWS-ACL as configurable

### ISSUE THREAD

**Issue by abhiCR7** [benjreinhart/react-native-aws3#5]
Right now by default the AWS-ACL is set to "public-read". 
But for my use case I want it to be configurable.
So i think we can pick this value from options and make it default to "public-read".
Please let me know if we can do this.
If you want I can raise pull request for this

**Comment by benjreinhart** [comment]
Yeah... it should be configurable. I'd be happy to have a PR submitted :)

**Comment by abhiCR7** [comment]
I have raised a PR, please release it as soon as possible.

**Comment by benjreinhart** [comment]
closed in #6 and released in 0.0.2

**Comment by abhiCR7** [comment]
Thanks :)
