### ISSUE TITLE
change library name: Generic javascript S3 uploader?

### ISSUE THREAD

**Issue by amanthegreatone** [benjreinhart/react-native-aws3#65]
Not an issue per se, I am using this for uploading to s3 from a react-native project and it works like a charm. 

Was developing a react project and used some other libs for uploading to s3 which were not working properly so I tried this and voila it works perfectly on react projects as well.

Maybe change the name of the lib so that people know it is not only for react-native?

**Comment by amanthegreatone** [comment]
the only change we need to make it to work on the web is to pass the file object from the html input element directly instead of constructing the file object for the mobile upload using the uri filepath.

**Comment by benjreinhart** [comment]
Yeah although it uses APIs that I believe are newer, so browser support is likely limited.
