### ISSUE TITLE
Could not find a declaration file for module 'react-native-aws3

### ISSUE THREAD

**Issue by LuisArturoMR** [benjreinhart/react-native-aws3#88]
> Could not find a declaration file for module 'react-native-aws3'. '/Users/luisarturomendozareyes/Documents/Mirak/WeOk/weok-app/node_modules/react-native-aws3/index.js' implicitly has an 'any' type.
>   Try `npm install @types/react-native-aws3` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-aws3';`

I get this error on my .js where I'm importing the node module.  I did npm i react-native-aws...

Do you have any idea of whats going on? 

![image](https://user-images.githubusercontent.com/4065361/62254973-e777ed80-b3c0-11e9-8186-40cec7814542.png)
Import error

![image](https://user-images.githubusercontent.com/4065361/62254994-fb235400-b3c0-11e9-8b82-e2a924a1e4c1.png)
index.js of react-native-aws3

Thanks!

**Comment by umair-dpl** [comment]
add src/RNS3.js
