### ISSUE TITLE
Abort upload

### ISSUE THREAD

**Issue by valdman40** [benjreinhart/react-native-aws3#94]
i don't understand how is it possible to abort uploading. can someone show an example?

*edit * solution:
defined **this.rns3** and made an abort in another function:
```
upload() {
      this.rns3 = RNS3.put(file, options)
        .progress((e) => { })
        .then(response => {  })
        .catch(err => { });
  }

  abort() {
    if (this.rns3) {
      this.rns3.abort();
    }
  }
```

**Comment by AkshayUk** [comment]
+1 Did you find a way to abort uploads? I too am looking for this!

**Comment by valdman40** [comment]
yes actually the solution is preatty simple,
you will understand just by looking at my code, 
as you can see i defined **this.rns3** and i could make an abort in another function that way :
```
upload() {
      this.rns3 = RNS3.put(file, options)
        .progress((e) => { })
        .then(response => {  })
        .catch(err => { });
  }

  abort() {
    if (this.rns3) {
      this.rns3.abort();
    }
  }
```
