### ISSUE TITLE
Stream Closed

### ISSUE THREAD

**Issue by umair-dpl** [benjreinhart/react-native-aws3#95]
Possible Unhandled Promise Rejection :
Object {
  "headers": Object {},
  "status": 0,
  "text": "Stream Closed",
}

 let data = {
              type: "image/jpeg",
              uri: element.path,
              name: element.path.substring(element.path.lastIndexOf("/") + 1, element.path.length),
            };
//data is coming from anther function via parameter I have highlighted data
upload(url, data) {
  for (let file in data) {
let options=[];
 options = {
        keyPrefix:"media/" ,
      bucket: "your_bucket_name",
      region: "ap-southeast-1",
      accessKey: "accessKey",
      secretKey: "secretKey",
      successActionStatus: 201
    };
 try {
        RNS3.put(data[file], options)       
        console.log('RNS3 is: '+JSON.stringify(data[file]))     
     .then(response => {
        console.log(response)
            if (response.status !== 201) {     
              throw new Error("Failed to upload image to S3");
            }
            if (response.status == 201) {
              console.log('response is: '+response.status);
            }
          })
        .catch(err => console.log('S3 error: '+JSON.stringify(err))
           )
       } catch (error) {
         console.error('RNS3 catch error: '+JSON.stringify(error));
       }
}
}

**Comment by umair-dpl** [comment]
actually the issue was react-native : 0.62.0 
by downgrading it to 0.61.0 or 0.61.5 the put API runs with the success status

**Comment by vishaltristate** [comment]
Same issue. 

Any one solved it in 0.62.0 ?

**Comment by nabilalilipaly** [comment]
success uploaded with ios device, but got same error (stream closed) with android device. i'm using react-native 0.62.0

**Comment by albertczyz** [comment]
Why this issue was closed? react-ntive 0.62.2 still experiencing the same issue, stream closed, but only on Android.

**Comment by umair-dpl** [comment]
if anyone finds a fix for this comment here please I am opening it again

**Comment by vishaltristate** [comment]
check in release builds. In debug mode, it creates an issue.

**Comment by nabilalilipaly** [comment]
> check in release builds. In debug mode, it creates an issue.

@vishaltristate so, if we disable debug mode, this issue will automatically solved?

**Comment by nabilalilipaly** [comment]
i found the solution for this issue https://github.com/facebook/react-native/issues/28551#issuecomment-611085378

**Comment by Farmscraft** [comment]
Same issue in release build on android. Any one fixed?
react native : 0.62.1

**Comment by MAsif99** [comment]
Same issue in release build on android. Any one fixed?
    "react-native": "0.70.4",
